import type { Metadata } from "next";
import { Exo, Inter_Tight, Edu_AU_VIC_WA_NT_Hand } from "next/font/google";
import "./globals.css";

const exo = Exo({ subsets: ["latin"], weight: ["100", "200", "400", "700", "900"] });
const interTight = Inter_Tight({ subsets: ["latin"], weight: ["100", "200", "400", "700", "900"] });
const eduHand = Edu_AU_VIC_WA_NT_Hand({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fonts = { exo, interTight, eduHand };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={interTight.className}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
