import type { Metadata } from "next";
import { exo, interTight, eduHand, montserrat, raleway, manrope } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" 
      className={`${exo.className} ${eduHand.className}`}
      style={{
        "--font-inter-tight": interTight.style.fontFamily,
        "--font-exo": exo.style.fontFamily,
        "--font-edu-hand": eduHand.style.fontFamily,
        "--font-montserrat": montserrat.style.fontFamily,
        "--font-raleway": raleway.style.fontFamily,
        "--font-manrope": manrope.style.fontFamily,
      } as React.CSSProperties}
    >
      <body className={`${interTight.className} antialiased`}>{children}</body>
    </html>
  );
}
